package com.aas.ssw.business.entity;

import java.util.Date;

public class AekoTul extends AekoTulKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.POS
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String POS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.PL
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String PL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.NF_UA_I
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String NF_UA_I;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.PART_NUMBER
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String PART_NUMBER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.TUL_Z
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String TUL_Z;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.DESCRIPTION
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String DESCRIPTION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.CALC_WHT_ENG
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String CALC_WHT_ENG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.DRWG_DAT
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String DRWG_DAT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.SEE_DRAW
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String SEE_DRAW;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.B_REL
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String b_REL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.P_REL
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String p_REL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.KIZ
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String KIZ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.DS
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String DS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.FK
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String FK;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.TP
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String TP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.KD
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String KD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.TUL_G
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String TUL_G;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.D_STA
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String d_STA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.COST
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String COST;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.WW
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String WW;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.DMU
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String DMU;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.MOKZ
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String MOKZ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.ME
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String ME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.UMFANG_TACT
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String UMFANG_TACT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.PR_NUM
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private String PR_NUM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.CREATE_TIME
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private Date CREATE_TIME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.POS
     *
     * @return the value of TT_AEKO_TUL.POS
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getPOS() {
        return POS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.POS
     *
     * @param POS the value for TT_AEKO_TUL.POS
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setPOS(String POS) {
        this.POS = POS == null ? null : POS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.PL
     *
     * @return the value of TT_AEKO_TUL.PL
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getPL() {
        return PL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.PL
     *
     * @param PL the value for TT_AEKO_TUL.PL
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setPL(String PL) {
        this.PL = PL == null ? null : PL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.NF_UA_I
     *
     * @return the value of TT_AEKO_TUL.NF_UA_I
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getNF_UA_I() {
        return NF_UA_I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.NF_UA_I
     *
     * @param NF_UA_I the value for TT_AEKO_TUL.NF_UA_I
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setNF_UA_I(String NF_UA_I) {
        this.NF_UA_I = NF_UA_I == null ? null : NF_UA_I.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.PART_NUMBER
     *
     * @return the value of TT_AEKO_TUL.PART_NUMBER
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getPART_NUMBER() {
        return PART_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.PART_NUMBER
     *
     * @param PART_NUMBER the value for TT_AEKO_TUL.PART_NUMBER
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setPART_NUMBER(String PART_NUMBER) {
        this.PART_NUMBER = PART_NUMBER == null ? null : PART_NUMBER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.TUL_Z
     *
     * @return the value of TT_AEKO_TUL.TUL_Z
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getTUL_Z() {
        return TUL_Z;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.TUL_Z
     *
     * @param TUL_Z the value for TT_AEKO_TUL.TUL_Z
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setTUL_Z(String TUL_Z) {
        this.TUL_Z = TUL_Z == null ? null : TUL_Z.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.DESCRIPTION
     *
     * @return the value of TT_AEKO_TUL.DESCRIPTION
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.DESCRIPTION
     *
     * @param DESCRIPTION the value for TT_AEKO_TUL.DESCRIPTION
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.CALC_WHT_ENG
     *
     * @return the value of TT_AEKO_TUL.CALC_WHT_ENG
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getCALC_WHT_ENG() {
        return CALC_WHT_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.CALC_WHT_ENG
     *
     * @param CALC_WHT_ENG the value for TT_AEKO_TUL.CALC_WHT_ENG
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setCALC_WHT_ENG(String CALC_WHT_ENG) {
        this.CALC_WHT_ENG = CALC_WHT_ENG == null ? null : CALC_WHT_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.DRWG_DAT
     *
     * @return the value of TT_AEKO_TUL.DRWG_DAT
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getDRWG_DAT() {
        return DRWG_DAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.DRWG_DAT
     *
     * @param DRWG_DAT the value for TT_AEKO_TUL.DRWG_DAT
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setDRWG_DAT(String DRWG_DAT) {
        this.DRWG_DAT = DRWG_DAT == null ? null : DRWG_DAT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.SEE_DRAW
     *
     * @return the value of TT_AEKO_TUL.SEE_DRAW
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getSEE_DRAW() {
        return SEE_DRAW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.SEE_DRAW
     *
     * @param SEE_DRAW the value for TT_AEKO_TUL.SEE_DRAW
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setSEE_DRAW(String SEE_DRAW) {
        this.SEE_DRAW = SEE_DRAW == null ? null : SEE_DRAW.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.B_REL
     *
     * @return the value of TT_AEKO_TUL.B_REL
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getB_REL() {
        return b_REL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.B_REL
     *
     * @param b_REL the value for TT_AEKO_TUL.B_REL
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setB_REL(String b_REL) {
        this.b_REL = b_REL == null ? null : b_REL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.P_REL
     *
     * @return the value of TT_AEKO_TUL.P_REL
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getP_REL() {
        return p_REL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.P_REL
     *
     * @param p_REL the value for TT_AEKO_TUL.P_REL
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setP_REL(String p_REL) {
        this.p_REL = p_REL == null ? null : p_REL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.KIZ
     *
     * @return the value of TT_AEKO_TUL.KIZ
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getKIZ() {
        return KIZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.KIZ
     *
     * @param KIZ the value for TT_AEKO_TUL.KIZ
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setKIZ(String KIZ) {
        this.KIZ = KIZ == null ? null : KIZ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.DS
     *
     * @return the value of TT_AEKO_TUL.DS
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getDS() {
        return DS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.DS
     *
     * @param DS the value for TT_AEKO_TUL.DS
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setDS(String DS) {
        this.DS = DS == null ? null : DS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.FK
     *
     * @return the value of TT_AEKO_TUL.FK
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getFK() {
        return FK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.FK
     *
     * @param FK the value for TT_AEKO_TUL.FK
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setFK(String FK) {
        this.FK = FK == null ? null : FK.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.TP
     *
     * @return the value of TT_AEKO_TUL.TP
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getTP() {
        return TP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.TP
     *
     * @param TP the value for TT_AEKO_TUL.TP
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setTP(String TP) {
        this.TP = TP == null ? null : TP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.KD
     *
     * @return the value of TT_AEKO_TUL.KD
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getKD() {
        return KD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.KD
     *
     * @param KD the value for TT_AEKO_TUL.KD
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setKD(String KD) {
        this.KD = KD == null ? null : KD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.TUL_G
     *
     * @return the value of TT_AEKO_TUL.TUL_G
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getTUL_G() {
        return TUL_G;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.TUL_G
     *
     * @param TUL_G the value for TT_AEKO_TUL.TUL_G
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setTUL_G(String TUL_G) {
        this.TUL_G = TUL_G == null ? null : TUL_G.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.D_STA
     *
     * @return the value of TT_AEKO_TUL.D_STA
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getD_STA() {
        return d_STA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.D_STA
     *
     * @param d_STA the value for TT_AEKO_TUL.D_STA
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setD_STA(String d_STA) {
        this.d_STA = d_STA == null ? null : d_STA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.COST
     *
     * @return the value of TT_AEKO_TUL.COST
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getCOST() {
        return COST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.COST
     *
     * @param COST the value for TT_AEKO_TUL.COST
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setCOST(String COST) {
        this.COST = COST == null ? null : COST.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.WW
     *
     * @return the value of TT_AEKO_TUL.WW
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getWW() {
        return WW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.WW
     *
     * @param WW the value for TT_AEKO_TUL.WW
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setWW(String WW) {
        this.WW = WW == null ? null : WW.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.DMU
     *
     * @return the value of TT_AEKO_TUL.DMU
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getDMU() {
        return DMU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.DMU
     *
     * @param DMU the value for TT_AEKO_TUL.DMU
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setDMU(String DMU) {
        this.DMU = DMU == null ? null : DMU.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.MOKZ
     *
     * @return the value of TT_AEKO_TUL.MOKZ
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getMOKZ() {
        return MOKZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.MOKZ
     *
     * @param MOKZ the value for TT_AEKO_TUL.MOKZ
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setMOKZ(String MOKZ) {
        this.MOKZ = MOKZ == null ? null : MOKZ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.ME
     *
     * @return the value of TT_AEKO_TUL.ME
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getME() {
        return ME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.ME
     *
     * @param ME the value for TT_AEKO_TUL.ME
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setME(String ME) {
        this.ME = ME == null ? null : ME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.UMFANG_TACT
     *
     * @return the value of TT_AEKO_TUL.UMFANG_TACT
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getUMFANG_TACT() {
        return UMFANG_TACT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.UMFANG_TACT
     *
     * @param UMFANG_TACT the value for TT_AEKO_TUL.UMFANG_TACT
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setUMFANG_TACT(String UMFANG_TACT) {
        this.UMFANG_TACT = UMFANG_TACT == null ? null : UMFANG_TACT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.PR_NUM
     *
     * @return the value of TT_AEKO_TUL.PR_NUM
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public String getPR_NUM() {
        return PR_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.PR_NUM
     *
     * @param PR_NUM the value for TT_AEKO_TUL.PR_NUM
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setPR_NUM(String PR_NUM) {
        this.PR_NUM = PR_NUM == null ? null : PR_NUM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.CREATE_TIME
     *
     * @return the value of TT_AEKO_TUL.CREATE_TIME
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public Date getCREATE_TIME() {
        return CREATE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.CREATE_TIME
     *
     * @param CREATE_TIME the value for TT_AEKO_TUL.CREATE_TIME
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setCREATE_TIME(Date CREATE_TIME) {
        this.CREATE_TIME = CREATE_TIME;
    }
}