package com.aas.ssw.business.entity;

public class AekoTulKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.TUL_ID
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private Long TUL_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_AEKO_TUL.LNR
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    private Long LNR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.TUL_ID
     *
     * @return the value of TT_AEKO_TUL.TUL_ID
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public Long getTUL_ID() {
        return TUL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.TUL_ID
     *
     * @param TUL_ID the value for TT_AEKO_TUL.TUL_ID
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setTUL_ID(Long TUL_ID) {
        this.TUL_ID = TUL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_AEKO_TUL.LNR
     *
     * @return the value of TT_AEKO_TUL.LNR
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public Long getLNR() {
        return LNR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_AEKO_TUL.LNR
     *
     * @param LNR the value for TT_AEKO_TUL.LNR
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    public void setLNR(Long LNR) {
        this.LNR = LNR;
    }
}