package com.aas.ssw.business.example.dao;

import com.aas.ssw.business.example.entity.Groups;

public interface GroupsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbg.generated Wed Apr 18 16:14:04 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbg.generated Wed Apr 18 16:14:04 CST 2018
     */
    int insert(Groups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbg.generated Wed Apr 18 16:14:04 CST 2018
     */
    int insertSelective(Groups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbg.generated Wed Apr 18 16:14:04 CST 2018
     */
    Groups selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbg.generated Wed Apr 18 16:14:04 CST 2018
     */
    int updateByPrimaryKeySelective(Groups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbg.generated Wed Apr 18 16:14:04 CST 2018
     */
    int updateByPrimaryKey(Groups record);
}