package com.aas.ssw.business.example.dao;

import com.aas.ssw.business.example.entity.GroupRole;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GroupRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbg.generated Wed Apr 18 15:24:50 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbg.generated Wed Apr 18 15:24:50 CST 2018
     */
    int insert(GroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbg.generated Wed Apr 18 15:24:50 CST 2018
     */
    int insertSelective(GroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbg.generated Wed Apr 18 15:24:50 CST 2018
     */
    GroupRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbg.generated Wed Apr 18 15:24:50 CST 2018
     */
    int updateByPrimaryKeySelective(GroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbg.generated Wed Apr 18 15:24:50 CST 2018
     */
    int updateByPrimaryKey(GroupRole record);

    List<Integer> findRoleIdListByGroupIdList(@Param("groupIdList") List<Integer> groupIdList);
}