package com.aas.ssw.business.example.dao;

import com.aas.ssw.business.example.entity.Resource;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ResourceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Wed Apr 18 15:25:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Wed Apr 18 15:25:22 CST 2018
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Wed Apr 18 15:25:22 CST 2018
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Wed Apr 18 15:25:22 CST 2018
     */
    Resource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Wed Apr 18 15:25:22 CST 2018
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Wed Apr 18 15:25:22 CST 2018
     */
    int updateByPrimaryKey(Resource record);


    List<Resource> findByResourceIdList(@Param("resourceIdList") List<Integer> ResourceIdList);

    List<Resource> findAll();

    List<Resource> findByUserId(Integer userId);
}