package com.aas.ssw.business.example.dao;

import com.aas.ssw.business.example.entity.RoleResource;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RoleResourceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated Wed Apr 18 15:26:17 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated Wed Apr 18 15:26:17 CST 2018
     */
    int insert(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated Wed Apr 18 15:26:17 CST 2018
     */
    int insertSelective(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated Wed Apr 18 15:26:17 CST 2018
     */
    RoleResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated Wed Apr 18 15:26:17 CST 2018
     */
    int updateByPrimaryKeySelective(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated Wed Apr 18 15:26:17 CST 2018
     */
    int updateByPrimaryKey(RoleResource record);


    List<Integer> findResourceIdListByRoleIdList(@Param("roleIdLis") List<Integer> roleIdList);
}