package com.aas.ssw.business.example.entity;

public class GroupRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_role.id
     *
     * @mbg.generated Wed Apr 18 15:24:50 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_role.groupId
     *
     * @mbg.generated Wed Apr 18 15:24:50 CST 2018
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_role.roleId
     *
     * @mbg.generated Wed Apr 18 15:24:50 CST 2018
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_role.id
     *
     * @return the value of group_role.id
     *
     * @mbg.generated Wed Apr 18 15:24:50 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_role.id
     *
     * @param id the value for group_role.id
     *
     * @mbg.generated Wed Apr 18 15:24:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_role.groupId
     *
     * @return the value of group_role.groupId
     *
     * @mbg.generated Wed Apr 18 15:24:50 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_role.groupId
     *
     * @param groupId the value for group_role.groupId
     *
     * @mbg.generated Wed Apr 18 15:24:50 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_role.roleId
     *
     * @return the value of group_role.roleId
     *
     * @mbg.generated Wed Apr 18 15:24:50 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_role.roleId
     *
     * @param roleId the value for group_role.roleId
     *
     * @mbg.generated Wed Apr 18 15:24:50 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}