package com.aas.ssw.business.example.entity;

public class Resource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbg.generated Wed Apr 18 15:25:22 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.name
     *
     * @mbg.generated Wed Apr 18 15:25:22 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.url
     *
     * @mbg.generated Wed Apr 18 15:25:22 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.status
     *
     * @mbg.generated Wed Apr 18 15:25:22 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbg.generated Wed Apr 18 15:25:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbg.generated Wed Apr 18 15:25:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.name
     *
     * @return the value of resource.name
     *
     * @mbg.generated Wed Apr 18 15:25:22 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.name
     *
     * @param name the value for resource.name
     *
     * @mbg.generated Wed Apr 18 15:25:22 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.url
     *
     * @return the value of resource.url
     *
     * @mbg.generated Wed Apr 18 15:25:22 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.url
     *
     * @param url the value for resource.url
     *
     * @mbg.generated Wed Apr 18 15:25:22 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.status
     *
     * @return the value of resource.status
     *
     * @mbg.generated Wed Apr 18 15:25:22 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.status
     *
     * @param status the value for resource.status
     *
     * @mbg.generated Wed Apr 18 15:25:22 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}