package com.aas.ssw.business.example.entity;

public class UserGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.id
     *
     * @mbg.generated Wed Apr 18 15:26:59 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.userId
     *
     * @mbg.generated Wed Apr 18 15:26:59 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.groupId
     *
     * @mbg.generated Wed Apr 18 15:26:59 CST 2018
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.id
     *
     * @return the value of user_group.id
     *
     * @mbg.generated Wed Apr 18 15:26:59 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.id
     *
     * @param id the value for user_group.id
     *
     * @mbg.generated Wed Apr 18 15:26:59 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.userId
     *
     * @return the value of user_group.userId
     *
     * @mbg.generated Wed Apr 18 15:26:59 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.userId
     *
     * @param userId the value for user_group.userId
     *
     * @mbg.generated Wed Apr 18 15:26:59 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.groupId
     *
     * @return the value of user_group.groupId
     *
     * @mbg.generated Wed Apr 18 15:26:59 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.groupId
     *
     * @param groupId the value for user_group.groupId
     *
     * @mbg.generated Wed Apr 18 15:26:59 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}