package com.aas.ssw.business.dao;

import com.aas.ssw.business.entity.KpiInfo;

public interface KpiInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:52:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:52:01 CST 2018
     */
    int insert(KpiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:52:01 CST 2018
     */
    int insertSelective(KpiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:52:01 CST 2018
     */
    KpiInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:52:01 CST 2018
     */
    int updateByPrimaryKeySelective(KpiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:52:01 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(KpiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:52:01 CST 2018
     */
    int updateByPrimaryKey(KpiInfo record);
}