package com.aas.ssw.business.dao;

import com.aas.ssw.business.entity.KpiInfo;
import com.aas.ssw.business.entity.KpiInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KpiInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:47:48 CST 2018
     */
    int countByExample(KpiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:47:48 CST 2018
     */
    int deleteByExample(KpiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:47:48 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:47:48 CST 2018
     */
    int insert(KpiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:47:48 CST 2018
     */
    int insertSelective(KpiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:47:48 CST 2018
     */
    List<KpiInfo> selectByExampleWithBLOBs(KpiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:47:48 CST 2018
     */
    List<KpiInfo> selectByExample(KpiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:47:48 CST 2018
     */
    KpiInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:47:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") KpiInfo record, @Param("example") KpiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:47:48 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") KpiInfo record, @Param("example") KpiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:47:48 CST 2018
     */
    int updateByExample(@Param("record") KpiInfo record, @Param("example") KpiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:47:48 CST 2018
     */
    int updateByPrimaryKeySelective(KpiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:47:48 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(KpiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbggenerated Fri Mar 09 10:47:48 CST 2018
     */
    int updateByPrimaryKey(KpiInfo record);
}