package com.aas.ssw.business.example.dao.two;

import com.aas.ssw.business.example.entity.AekoTul;
import com.aas.ssw.business.example.entity.AekoTulKey;

public interface AekoTulDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_AEKO_TUL
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    int deleteByPrimaryKey(AekoTulKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_AEKO_TUL
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    int insert(AekoTul record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_AEKO_TUL
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    int insertSelective(AekoTul record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_AEKO_TUL
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    AekoTul selectByPrimaryKey(AekoTulKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_AEKO_TUL
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    int updateByPrimaryKeySelective(AekoTul record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_AEKO_TUL
     *
     * @mbg.generated Mon Mar 12 09:59:17 CST 2018
     */
    int updateByPrimaryKey(AekoTul record);
}