package com.aas.ssw.business.dao.one;

import com.aas.ssw.business.entity.KpiInfo;

/**
 * @author xl
 */
public interface KpiInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbg.generated Fri Mar 09 11:01:41 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbg.generated Fri Mar 09 11:01:41 CST 2018
     */
    int insert(KpiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbg.generated Fri Mar 09 11:01:41 CST 2018
     */
    int insertSelective(KpiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbg.generated Fri Mar 09 11:01:41 CST 2018
     */
    KpiInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbg.generated Fri Mar 09 11:01:41 CST 2018
     */
    int updateByPrimaryKeySelective(KpiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbg.generated Fri Mar 09 11:01:41 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(KpiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kpi_info
     *
     * @mbg.generated Fri Mar 09 11:01:41 CST 2018
     */
    int updateByPrimaryKey(KpiInfo record);
}